"""add hnsw cosine index on chunks.embedding

Revision ID: 2532ce12ad44
Revises: 867a8d93a871
Create Date: 2026-08-11 09:18:32.373065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2532ce12ad44'
down_revision: Union[str, None] = '867a8d93a871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunks_embedding_hnsw_cosine', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_embedding_hnsw_cosine', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
