"""drop uploaded_by from documents

Revision ID: 6ed2e64113b3
Revises: 2532ce12ad44
Create Date: 2026-08-12 08:05:16.726982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ed2e64113b3'
down_revision: Union[str, None] = '2532ce12ad44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_uploaded_by_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'uploaded_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_uploaded_by_fkey', 'documents', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###
